In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../../datasets/iris/iris.csv")
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [41]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [4]:
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

In [5]:
tls.set_credentials_file(username="jmcirot",api_key="AxBSumBTAf6pjxclrQxJ")

In [6]:
traces = []
legend = {
    0:False,
         1:False,
         2:False,
         3:False
}
colors = {
    "setosa":'rgb(255,127,20)',
    "versicolor":'rgb(31,220,120)',
    "virginica":'rgb(44,50,180)'
}
for col in range(4):
    for key in colors:
        traces.append(Histogram(x=X[Y==key,col],
                                opacity=0.65,
                                xaxis="x%s"%(col+1),
                                marker=Marker(color=colors[key])
                               ,name=key,showlegend=legend[col])
                     )
data = Data(traces)
layout = Layout(barmode="overlay",
               xaxis=XAxis(domain=[0,0.25],title="Length. Sepal (cm)"),
               xaxis2=XAxis(domain=[0.3,0.5],title="Width. Sepal (cm)"),
               xaxis3=XAxis(domain=[0.55,0.75],title="Length. Petal (cm)"),
               xaxis4=XAxis(domain=[0.8,1.0],title="Width. Petal (cm)"),
               yaxis=YAxis(title="Frequency"))
                
fig = Figure(data=data,layout=layout)
py.iplot(fig)

/Users/Ivan/anaconda2/lib/python2.7/site-packages/plotly/graph_objs/_deprecations.py:426: DeprecationWarning:

plotly.graph_objs.Marker is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Marker
  - plotly.graph_objs.histogram.selected.Marker
  - etc.


/Users/Ivan/anaconda2/lib/python2.7/site-packages/plotly/graph_objs/_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.


/Users/Ivan/anaconda2/lib/python2.7/site-packages/plotly/graph_objs/_deprecations.py:531: DeprecationWarning:

plotly.graph_objs.XAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.XAxis
  - plotly.graph_objs.layout.scene.XAxis


/Users/Ivan/anaconda2/lib/python2.7/site-package

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
X_standar = StandardScaler().fit_transform(X)

### Calculated the descomposition 

In [9]:
from IPython.display import Latex,Math,display

In [10]:
display(Math(r'\sigma_{jk} = \frac{1}{n-1}\sum_{i=1}^m (x_{ij} - \overline{x_j})(x_{ik} - \overline(x_k))'))

<IPython.core.display.Math object>

In [11]:
import numpy as np

In [12]:
mean_vec = np.mean(X_standar, axis=0)

In [13]:
cov_matrix = (X_standar - mean_vec).T.dot((X_standar - mean_vec))/(X_standar.shape[0] - 1)

In [14]:
cov_matrix = np.cov(X_standar.T)

In [15]:
eig_values, eig_vectors = np.linalg.eig(cov_matrix)

### Using the covariance matriz

In [16]:
corr_matrix = np.corrcoef(X_standar.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [17]:
eig_values, eig_vectors = np.linalg.eig(corr_matrix)

### Singular value decomposition

In [18]:
u,s,v = np.linalg.svd(X_standar.T)

## Principal component

In [19]:
for ev in eig_vectors:
    print "The lenght of the EV is:%s"%np.linalg.norm(ev)

The lenght of the EV is:0.9999999999999998
The lenght of the EV is:1.0000000000000002
The lenght of the EV is:0.9999999999999999
The lenght of the EV is:1.0000000000000002


In [20]:
eigen_pairs = [(np.abs(eig_values[i]),eig_vectors[i])for i in range(len(eig_vectors))]
eigen_pairs

[(2.9184978165319952,
  array([ 0.52106591, -0.37741762, -0.71956635,  0.26128628])),
 (0.914030471468069,
  array([-0.26934744, -0.92329566,  0.24438178, -0.12350962])),
 (0.14675687557131503,
  array([ 0.5804131 , -0.02449161,  0.14212637, -0.80144925])),
 (0.02071483642861878,
  array([ 0.56485654, -0.06694199,  0.63427274,  0.52359713]))]

In [25]:
for ep in eigen_pairs:
    print ep[0]

2.9184978165319952
0.914030471468069
0.14675687557131503
0.02071483642861878


In [29]:
total_sum = sum(eig_values)
var_exp = [(i/total_sum)*100 for i in eig_values]
sum_var = np.cumsum(var_exp)
print sum_var

[ 72.96244541  95.8132072   99.48212909 100.        ]


In [32]:
plot1 = Bar(x=["CP %s"% i for i in range(1,5)],y = var_exp,showlegend=False)
plot2 = Scatter(x=["CP %s"% i for i in range(1,5)],y = sum_var,showlegend=False)
data = Data([plot1,plot2])
layout = Layout(xaxis=XAxis(title="Principal component"),
               yaxis=YAxis(title="%Explained percentage"))
fig = Figure(data,layout)
py.iplot(fig)

In [37]:
W = np.hstack((eigen_pairs[0][1].reshape(4,1),
             eigen_pairs[1][1].reshape(4,1)))
W

array([[ 0.52106591, -0.26934744],
       [-0.37741762, -0.92329566],
       [-0.71956635,  0.24438178],
       [ 0.26128628, -0.12350962]])

### Projecting the new vectorial sub-space

In [38]:
Y = X_standar.dot(W)

In [43]:
results = []

for name in ("setosa","versicolor",'virginica'):
    result = Scatter(x=Y[y==name,0],y = Y[y==name, 1],
                    mode="markers",name=name,
                    marker=Marker(size=12,line = Line(color='rgba(220,220,220,0.15)',width=0.5),
                                 opacity=0.8))
    results.append(result)
data = Data(results)
layout = Layout(showlegend=True, scene= Scene(xaxis=XAxis(title="Principal component 1"),
                                             yaxis=YAxis(title="Principal component 2")))
fig = Figure(data=data,layout=layout)
py.iplot(fig)