In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression

In [5]:
data = pd.read_csv("../../datasets/ads/Advertising.csv")

In [6]:
feature_cols = ["TV","Radio","Newspaper"]

In [7]:
X = data[feature_cols]
Y = data["Sales"]

In [9]:
estimator = SVR(kernel="linear")
selector = RFE(estimator,2,step=1)
selector =selector.fit(X,Y)

In [10]:
selector.support_

array([ True,  True, False])

In [11]:
selector.ranking_

array([1, 1, 2])

In [13]:
X_pred = X[["TV","Radio"]]
model = LinearRegression()
model.fit(X_pred,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
model.intercept_

2.9210999124051362

In [15]:
model.coef_

array([0.04575482, 0.18799423])

In [18]:
model.score(X_pred,Y)

0.8971942610828956